export const ADD_CITY = "ADD_CITY";
export const ADD_CITY_SUCCESS = "ADD_CITY_SUCCESS";
export const ADD_CITY_ERROR = "ADD_CITY_ERROR";

export const UPDATE_CITY_INFO = "UPDATE_CITY_INFO";
export const UPDATE_CITY_INFO_SUCCESS = "UPDATE_CITY_INFO_SUCCESS";
export const UPDATE_CITY_INFO_ERROR = "UPDATE_CITY_INFO_ERROR";

export const GET_CURRENT_WEATHER = "GET_CURRENT_WEATHER";
export const GET_CURRENT_WEATHER_SUCCESS = "GET_CURRENT_WEATHER_SUCCESS";
export const GET_CURRENT_WEATHER_ERROR = "GET_CURRENT_WEATHER_ERROR";

export const SAVE_CITY = "SAVE_CITY";
export const REMOVE_CITY = "REMOVE_CITY";
